version: '3'
services:
    lemp:
        build:
            context: .
        image: nodejs-nginx-mariadb-stack
        ports:
            - "80:80"
            - "3306:3306"
            - "9229:9229"
        volumes:
            - ".:/server/lib"
            - "mysql:/var/lib/mysql"
volumes:
    mysql:
